#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  export GOPATH="$shome"
  PATH="$shome/bin:$PATH"

  local pth_example="google.golang.org/grpc/examples/helloworld"

  go get -u   "${pth_example}/greeter_client"
  go get -u   "${pth_example}/greeter_server"
  go generate "${pth_example}/..."

  "$shome/bin/greeter_server" &
  sleep 1
  "$shome/bin/greeter_client"
  exec 2>/dev/null
  pkill greeter_server
  wait
}

main "$@"
